# Generated by Django 5.2.1 on 2025-05-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='preset_location',
            new_name='present_location',
        ),
    ]
