# Generated by Django 5.2.1 on 2025-05-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='OirC9rZWYHXoWCFWnOl52mMqG3lu2oHj', editable=False, max_length=32, unique=True),
        ),
    ]
